language: shell
os: linux
dist: xenial
jobs:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: bsdtar gperf texinfo help2man gcc-multilib g++-multilib
    env: GDB
    script: ['travis_wait 25 make USE_DISTRIB=y USE_GDB=y gdb']
  - os: linux
    dist: xenial
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: bsdtar gperf texinfo help2man gcc-multilib g++-multilib
    env: ALL
    script: ['travis_wait 55 make USE_DISTRIB=y all']
  - os: osx
    env: GDB
    script: ['travis_wait 35 make USE_DISTRIB=y USE_GDB=y gdb']
  - os: osx
    env: ALL
    script: ['travis_wait 55 make USE_DISTRIB=y all']
after_failure:
- tail -50 distrib/*-error.log
before_script:
#  - ccache -s
#  - ccache --set-config=compression=true
  - cd $TRAVIS_BUILD_DIR
#after_script: ccache -s # show ccache stats
before_install:
- unset CC
- unset CXX
- |-
  case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export shell="$msys2 -mingw64 -full-path -here -c \$\* --"
        export msys2+=" -msys2 -c \$\* --"
        $msys2 pacman --sync --noconfirm --needed \
              autoconf \
              automake \
              mingw-w64-x86_64-libtool \
              mingw-w64-x86_64-toolchain \
              mingw-w64-x86_64-pkg-config pkg-config \
              unzip bsdtar wget patch bison gperf m4 texinfo help2man
        taskkill //IM gpg-agent.exe //F
        export MAKE=mingw32-make
        $msys2 pacman -Ss sed
        $msys2 sed --version
        ;;
    esac
before_cache:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      $msys2 pacman --sync --clean --noconfirm
      ;;
  esac
cache:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      directories:
      - $HOME/AppData/Local/Temp/chocolatey
      - /C/tools/msys64
      ;;
  esac
before_deploy:
- ls -al distrib/*
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LVi66iBI7R8Z4vCQlPe4eBR4rOkopbymIRb6RS5PdRyD+rZGi+oF4UVlqGkmrR/07b86sG1hAHYKLZpXwWOWJG+Gzor3WsncaQJVbo9uiXx51lkATiDhppLMk9Uhgox5hUqk6OrlThM9nfz5EgeHj4pNxUBYPNmf+ZCWINBSTKdkjZkWJQTdzX73UhaUtRAqljM6oEGkNALFwGTbMfkVQKG1jMX5x/i/bkslMhI3uHQOy1N+HvVwd+W+QBlx07OWfT2FC0pRF4CS0uMt1gbGbua8gT0DRz633Ob/2EytngiSbYfUPFEZ5La/hydpMt377gY7VLRcLFiDsZNoEBxGMoDrF2F5SiT/ARy3/OJbuC0ffPEfLtDlD0bBHQdXEsHhoADfDf4ou9voulxg33RmkDGuByh8rHirbUpaZdYy5lcw9s4haFaaS1pWNkfBBR3bmlYKKyu411KJWidmN4Scvu4uMUb0U7/UhJKJWB8q0nsHkJ6WoIvFraKdXQm+SHeVGyT4y4ZHqBKU8H6i9aNT5NEn2fvxS1Xutq2Yuz1KbSoi5cxMYry0XydTr1T0sadN+gEod11MiXx3fSiFxhfL3Ywbril1gh+AFo812oLXbPPB3DbLC02fmpIsJTn1ILHkPFryIDC+PuVsoyGTmpJxrNmT9hoBQ+aX1p+hreghoZE=
  file_glob: on # enable wildcarts
  overwrite: on
  file: distrib/*
  on:
    repo: Juppit/make-esp-sdk
    all_branches: true
notifications:
  email: false
