# Author: Peter Dobler (@Juppit)
# Last edit: 21.03.2020
#version: 0.1.{build}
version: '0.9.0'
image: Visual Studio 2017
environment:
  # Path for appveyor install and build_script
  PATH: C:\msys64\usr\bin
  CCACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\.ccache"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
  - MSYSTEM: Cygwin64
    BUILD: Cygwin64
    BUILD_TARGET: gdb
#  - MSYSTEM: MINGW64
#    BUILD: Mingw64
#    BUILD_TARGET: gdb
  - MSYSTEM: Cygwin64
    BUILD: Cygwin64
    BUILD_TARGET: all
#  - MSYSTEM: MINGW64
#    BUILD: Mingw64
#    BUILD_TARGET: all
  CHERE_INVOKING: 1
cache:
  - .ccache
build_script:
  - if "%BUILD_TARGET%" == "all" bash --login -c "make USE_DISTRIB=y -j$(expr $(nproc) + 1)"
  - if "%BUILD_TARGET%" == "gdb" bash --login -c "make USE_DISTRIB=y USE_GDB=y gdb"
#  - ls -al distrib
on_failure:
  - tail -100 distrib/%BUILD%-error.log
test: off
artifacts:
#- path: distrib/%BUILD%*.tar.gz
  path: distrib/*.tar.gz
  name: builds
deploy:
- provider: GitHub
  # create Personal Access Token at https://github.com/settings/tokens
  # and encrypt it on https://ci.appveyor.com/tools/encrypt
  auth_token:
    secure: 8vDpPaKNVqNmK3teDnIVZ9cIyjQ60vweSlhWtnC0GTtigKl+TMIv6mv6Zhwos4Q9
  #artifact: builds
  description: "Release from AppVeyor"